# ============================================================================
# AUTO-GENERATED by AgentKit v0.4.2
# ============================================================================
# Source: agentkit.yaml
# Checksum: sha256:7156478e080dcc45
# ContentHash: sha256:9ecf97d7e96cba7d
# Generated: 2026-03-01T21:53:49.077687
# 
# This file is automatically generated and managed by AgentKit:
#   - It will be auto-updated when agentkit.yaml config changes (old version backed up)
#   - To fully customize, remove this header comment
#   - After removing the header, AgentKit will no longer manage this file
# 
# Force regenerate command:
#   agentkit build --regenerate-dockerfile
# 
# ============================================================================

# Support custom base image
FROM agentkit-cn-beijing.cr.volces.com/base/py-simple:python3.12-bookworm-slim-latest

ENV UV_SYSTEM_PYTHON=1 UV_COMPILE_BYTECODE=1 PYTHONUNBUFFERED=1 DOCKER_CONTAINER=1

WORKDIR /app

COPY requirements.txt requirements.txt

RUN uv pip install -r requirements.txt

# Copy entire project
COPY . .

EXPOSE 8000

CMD ["python", "-m", "agentkit-agent"]